//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetStatic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetStatic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array elements cannot be null, empty, or whitespace.
        /// </summary>
        internal static string Err_ArrayElementNullOrWhitespace {
            get {
                return ResourceManager.GetString("Err_ArrayElementNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is not configured as an HTTP service..
        /// </summary>
        internal static string Err_HostNotHttpService {
            get {
                return ResourceManager.GetString("Err_HostNotHttpService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid destination root folder. Specified folder does not exist..
        /// </summary>
        internal static string Err_InvalidDestinationRoot {
            get {
                return ResourceManager.GetString("Err_InvalidDestinationRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required value for Default-File-Extension configuration setting..
        /// </summary>
        internal static string Err_MissingDefaultFileExtension {
            get {
                return ResourceManager.GetString("Err_MissingDefaultFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required value for Default-File-Name configuration setting..
        /// </summary>
        internal static string Err_MissingDefaultFileName {
            get {
                return ResourceManager.GetString("Err_MissingDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization is enabled but no minifier selector provided..
        /// </summary>
        internal static string Err_OptimizeWithoutChooser {
            get {
                return ResourceManager.GetString("Err_OptimizeWithoutChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route for resource is not well-formed. Expected a {0} URI..
        /// </summary>
        internal static string Err_RouteForResourceNotWellFormed {
            get {
                return ResourceManager.GetString("Err_RouteForResourceNotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null, emtpy, or whitespace..
        /// </summary>
        internal static string Err_ValueCannotBeNullEmptyWhitespace {
            get {
                return ResourceManager.GetString("Err_ValueCannotBeNullEmptyWhitespace", resourceCulture);
            }
        }
    }
}
